version: '3.3'

services:

  web:
    build: .
    ports:
      - 443:5000
    links:
      - db:database

  db:
    image: postgres
    restart: always
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: qwerty123
    ports:
      - 5432:5432